server:
  port: 5001

spring:
  jpa:
#    PostgreSQL JPA Settings
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
    # MySQL 8 JPA Settings
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    # PostgreSQL Data Source
#    url: jdbc:postgresql://localhost:5432/bankAccount
#    username: postgres
#    password: toor
    # MySQL 8 Data Source
    url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExists=true
    username: root
    password: toor
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'